Fix lineHash.hasOwnProperty might be contaminated
if calling method like dmp.diff_linesToChars_('hasOwnProperty', ' ') will throw TypeError: lineHash.hasOwnProperty is not a function
since the lineHash is a instance of Object, the method can be overwritten while walking through the text lines.

To avoid this, we can use Object.prototype.hasOwnProperty.call(lineHash, line) that make it always can call hasOwnProperty properly.

Update diff_match_patch_uncompressed.js